<<<<<<< HEAD
name = "remix"
=======
name = "React Router"
>>>>>>> 9e37be4 (push)
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
<<<<<<< HEAD
dev = "npx prisma migrate deploy && npm exec remix vite:dev"
=======
dev = "npx prisma migrate deploy && npm exec react-router dev"
>>>>>>> 9e37be4 (push)
