# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d0f0a8d5f840d3c052926137df15123"
name = "section-addict"
application_url = "https://clause-accepts-immigrants-staffing.trycloudflare.com"
embedded = true
handle = "section-addict-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products,write_themes"

[auth]
redirect_urls = ["https://clause-accepts-immigrants-staffing.trycloudflare.com/auth/callback", "https://clause-accepts-immigrants-staffing.trycloudflare.com/auth/shopify/callback", "https://clause-accepts-immigrants-staffing.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
